#' @title Get Cost-of-Goods-Sold-to-Revenue-Ratio
#'
#' @description Wrapper function for fetching data from
#' [gurufocus.com](https://www.gurufocus.com/term/cogs2rev/AAPL/).
#'
#' @usage get_cogs_to_revenue(df)
#'
#' @param df data.frame. Data frame with column 'symbol' containing at least one
#' valid stock ticker symbol.
#'
#' @return Input data.frame supplemented by the company's available
#' **Cost-of-Goods-Sold-to-Revenue-Ratio** data.
#' @export
#'
#' @examples
#' df <- data.frame('symbol' = 'AAPL')
#' res <- get_cogs_to_revenue(df)
#'
#' @details
#' The Asset-Turnover-Ratio measures the direct cost attributed to the
#' production of the products sold relative to the total revenue generated by
#' the company over the same time period. Higher values may indicate
#' inefficiencies in procurement and/or production processes.

get_cogs_to_revenue <- function(df) {

  pfx <- 'cogs2rev'
  url <- 'https://www.gurufocus.com/term/cogs2rev/'
  xpath_tbl <- '//*[@id="target_def_historical_data"]/div[2]/div/table'
  xpath_txt <- '//*[@id="def_body_detail_height"]/font[1]'

  res <- suppressWarnings(scrape_key_fig(df, url, pfx, xpath_txt, xpath_tbl))

  return(res)
}
